sudo: false

language: python
python:
  - "3.6"
  - "3.5"
  - "2.7"

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda create -n taxcalc-dev python=$TRAVIS_PYTHON_VERSION;
  - source activate taxcalc-dev
  - conda env update -f environment.yml
  - if [ $TRAVIS_EVENT_TYPE == 'cron' ]; then conda remove  numba; fi
  - pip install pytest-pep8
  - pip install coverage
  - pip install codecov
  - python setup.py install


# command to run tests, e.g. python setup.py test
script:
  - python -c "import taxcalc"; coverage run -m py.test -v -m "not requires_pufcsv" --pep8

after_success:
  - codecov
