# This appveyor environment is loosely based on one at
# https://github.com/conda/conda/blob/master/appveyor.yml

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous_integration\\run_with_env.cmd"

  matrix:
    # Since appveyor is quite slow, we only use a single configuration
    - PYTHON: "3.7"
      ARCH: "64"
      CONDA_ENV: taxcalc-dev

init:
  # Use AppVeyor's provided Miniconda, which is available from
  # https://www.appveyor.com/docs/installed-software#python
  - if "%ARCH%" == "64" set MINICONDA=C:\Miniconda36-x64
  - if "%ARCH%" == "32" set MINICONDA=C:\Miniconda36
  - set PATH=%MINICONDA%;%MINICONDA%/Scripts;%MINICONDA%/Library/bin;%PATH%

install:
  # Update to a recent version of conda that is consistent with Python 3.6
  - conda install -q -y conda>=4.3.0
  - continuous_integration\\setup_conda_environment.cmd

build_script:
  - continuous_integration\\build.cmd

test_script:
  # %CMD_IN_ENV% is needed for distutils/setuptools-based tests
  # on certain build configurations.
  - "%CMD_IN_ENV% continuous_integration\\run_tests.cmd"
